FROM maven:3.5.2-jdk-8-alpine AS MAVEN_BUILD

MAINTAINER Jai Singh Saini

COPY pom.xml /build/
COPY src /build/src/

WORKDIR /build/
RUN mvn package

FROM openjdk:8-jre-alpine

WORKDIR /tmp

COPY --from=MAVEN_BUILD /build/target/ShoppingCart-0.0.1-SNAPSHOT.jar /tmp/

ENTRYPOINT ["java", "-jar", "ShoppingCart-0.0.1-SNAPSHOT.jar"]